// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace FireBrowserWinUi3DataCore.Migrations;

[DbContext(typeof(HistoryContext))]
partial class HistoryContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

        modelBuilder.Entity("FireBrowserWinUi3DataCore.Models.HistoryItem", b =>
            {
                b.Property<int>("id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<int>("hidden")
                    .HasColumnType("INTEGER");

                b.Property<string>("last_visit_time")
                    .HasColumnType("TEXT");

                b.Property<string>("title")
                    .HasColumnType("TEXT");

                b.Property<int>("typed_count")
                    .HasColumnType("INTEGER");

                b.Property<string>("url")
                    .HasColumnType("TEXT");

                b.Property<int>("visit_count")
                    .HasColumnType("INTEGER");

                b.HasKey("id");

                b.ToTable("Urls");
            });
#pragma warning restore 612, 618
    }
}
