// <auto-generated />
using FireBrowserWinUi3DataCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
#nullable disable

namespace FireBrowserWinUi3DataCore.Migrations.Download;

[DbContext(typeof(DownloadContext))]
partial class DownloadContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

        modelBuilder.Entity("FireBrowserWinUi3DataCore.Models.DownloadItem", b =>
            {
                b.Property<int>("id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("current_path")
                    .HasColumnType("TEXT");

                b.Property<string>("end_time")
                    .HasColumnType("TEXT");

                b.Property<string>("guid")
                    .HasColumnType("TEXT");

                b.Property<long>("start_time")
                    .HasColumnType("INTEGER");

                b.HasKey("id");

                b.ToTable("Downloads");
            });
#pragma warning restore 612, 618
    }
}
